# PPO 强化学习对齐阶段配置
extends: default

stage: ppo
n_epochs: 2
batch_size: 50
gradient_accumulation_steps: 10
eval_batch_interval: 10

model:
  max_position_embeddings: 2048
  original_max_position_embeddings: 512
  rope:
    rope_type: yarn

lr:
  initial: 1.0e-5
  scheduler: false
  value:
    initial: 5.0e-5
    scheduler: false

ppo:
  epochs: 2
  batch_size: 5
  vf_coef: 0.5
  kl_beta: 0.01
  kl_estimator: k3
  normalize_rewards: true
  normalize_method: RunningMeanStd
  clip_eps: 0.1
  gamma: 1.0
  lam: 0.95
  gen:
    max_seq_len: 2048
    temperature: 1.0
    p: 0.9
